### ISSUE TITLE
[BUG] - panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by roninro** [go-co-op/gocron#282]
```go

func main() {

	s := gocron.NewScheduler(time.UTC)
	s.StartAsync()

	t := time.Date(2022, 1, 24, 0, 0, 0, 0, time.UTC)

	_, err := s.Every(1).Monday().StartAt(t).Do(task)

	if err != nil {
		log.Println(err)
	}

	ch := make(chan bool)
	<-ch
}
```

this panic 

```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/go-co-op/gocron.(*Scheduler).scheduleNextRun(0xc000144000, 0xc000146180)
        /Users/xxxx/go/pkg/mod/github.com/go-co-op/gocron@v1.11.0/scheduler.go:177 +0x572
github.com/go-co-op/gocron.(*Scheduler).Do(0xc000144000, {0x10bc2c0, 0x10db718}, {0x0, 0x0, 0x0})
        /Users/xxx/go/pkg/mod/github.com/go-co-op/gocron@v1.11.0/scheduler.go:771 +0x525
main.main()
        /Users/xxx/GolandProjects/awesomeProject/main.go:38 +0x25c
```

**Comment by AlexanderSutul** [comment]
@JohnRoesler I'd like to figure out what is going on here. Could you assign it to me?
