### ISSUE TITLE
[BUG] - Please add descriptive title

### ISSUE THREAD

**Issue by LCTDDL** [go-co-op/gocron#287]
// painc
package main

import (
	"fmt"
	"github.com/go-co-op/gocron"
	"time"
)

var task = func() {
	fmt.Println(time.Now())
}

func main() {
	fmt.Println("Hello Work")
	s := gocron.NewScheduler(time.UTC)

        //  //  //  //  //  //  //  //  
	s.SingletonMode()  //  

	job, _ := s.Every("3s").Do(task)  // is painc 
        //job, _ := s.Every(3).Second().Do(task)  // no painc 

	s.StartAsync()

	fmt.Println(s.Jobs()[0])

	fmt.Println("Last run:", job.LastRun())
	select {}
}

// out :

Hello Work
&{{{0 0} 0 0 0 0} {0x89d220 [] main.glob..func1 {false 0 1} 0xc000044400 <nil> <nil> <nil>} 0 3000000000 7 false 0 {0 0 <nil>} <nil> {0 0 <nil>} {299384300 63779899969 <nil>} [] [] [] 0 0xc0000521e0 <nil>}
Last run: 0001-01-01 00:00:00 +0000 UTC
panic: runtime error: invalid memory address or nil pointer dereference

runtime/debug.Stack()
	C:/Go/src/runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0x8ac3e0, 0x979190})
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:188 +0x3b
panic({0x8ac3e0, 0x979190})
	C:/Go/src/runtime/panic.go:1038 +0x215
github.com/go-co-op/gocron.(*executor).start.func1.1()
	D:/ProgramGo/Packages/pkg/mod/github.com/go-co-op/gocron@v1.11.0/executor.go:89 +0x41
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc000049e4e, 0xc000050180, 0x8b3dc0)
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:193 +0x6f
golang.org/x/sync/singleflight.(*Group).doCall(0x8abea0, 0xc00007a630, {0x8bee31, 0x4}, 0x8996c8)
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:195 +0xad
golang.org/x/sync/singleflight.(*Group).Do(0xc000044400, {0x8bee31, 0x4}, 0xc000049f38)
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154
github.com/go-co-op/gocron.(*executor).start.func1()
	D:/ProgramGo/Packages/pkg/mod/github.com/go-co-op/gocron@v1.11.0/executor.go:85 +0x1cf
created by github.com/go-co-op/gocron.(*executor).start
	D:/ProgramGo/Packages/pkg/mod/github.com/go-co-op/gocron@v1.11.0/executor.go:50 +0x76

goroutine 8 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:165 +0x2b3
golang.org/x/sync/singleflight.(*Group).doCall(0x8abea0, 0xc00007a630, {0x8bee31, 0x4}, 0x8996c8)
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:200 +0xc8
golang.org/x/sync/singleflight.(*Group).Do(0xc000044400, {0x8bee31, 0x4}, 0xc000049f38)
	D:/ProgramGo/Packages/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154
github.com/go-co-op/gocron.(*executor).start.func1()
	D:/ProgramGo/Packages/pkg/mod/github.com/go-co-op/gocron@v1.11.0/executor.go:85 +0x1cf
created by github.com/go-co-op/gocron.(*executor).start
	D:/ProgramGo/Packages/pkg/mod/github.com/go-co-op/gocron@v1.11.0/executor.go:50 +0x76

进程 已完成，退出代码为 2

**Comment by LCTDDL** [comment]
重复
