### ISSUE TITLE
[BUG] - Starting and then stopping a scheduler twice causes a deadlock

### ISSUE THREAD

**Issue by grebneerg** [go-co-op/gocron#355]
### Describe the bug

When I start a scheduler, stop it, restart it, and then stop it again, it either crashes or blocks indefinitely, depending on whether I have added any jobs to it.

#### Without jobs
With the following code:
```go
package main

import "github.com/go-co-op/gocron"
import "fmt"
import "time"

func main() {
	cron := gocron.NewScheduler(time.Local)

	cron.StartAsync()
	fmt.Println("Started once")

	cron.Stop()
	fmt.Println("Stopped once")

	cron.StartAsync()
	fmt.Println("Started twice")

	cron.Stop()
	fmt.Println("Stopped twice")

	fmt.Println("finished")
}
```
The produced output is:
```
Started once
Stopped once
Started twice
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
github.com/go-co-op/gocron.(*Scheduler).stop(...)
        /Users/jagreenberg/alpha/gocode/pkg/mod/github.com/go-co-op/gocron@v1.15.0/scheduler.go:814
github.com/go-co-op/gocron.(*Scheduler).Stop(0xc00011a000)
        /Users/jagreenberg/alpha/gocode/pkg/mod/github.com/go-co-op/gocron@v1.15.0/scheduler.go:807 +0x7b
main.main()
        /Users/jagreenberg/Documents/testcron/main.go:21 +0x29a

goroutine 5 [select]:
github.com/go-co-op/gocron.(*executor).start(0xc0001080c0)
        /Users/jagreenberg/alpha/gocode/pkg/mod/github.com/go-co-op/gocron@v1.15.0/executor.go:46 +0xe5
created by github.com/go-co-op/gocron.(*Scheduler).start
        /Users/jagreenberg/alpha/gocode/pkg/mod/github.com/go-co-op/gocron@v1.15.0/scheduler.go:84 +0x6a
exit status 2
```

#### With a job
With the following code:
```go
package main

import "github.com/go-co-op/gocron"
import "fmt"
import "time"

func main() {
	cron := gocron.NewScheduler(time.Local)

	cron.StartAsync()
	fmt.Println("Started once")

	cron.Cron("@every 1s").Do(func() {
		fmt.Println("test")
	})

	cron.Stop()
	fmt.Println("Stopped once")

	cron.StartAsync()
	fmt.Println("Started twice")

	cron.Stop()
	fmt.Println("Stopped twice")

	fmt.Println("finished")
}
```
The produced output is:
```
Started once
Stopped once
Started twice
test
```
Even after ten more minutes, `test` is never printed again, and the program never completes.

### Version

go.mod:
```
module grebneerg.com/test/v2

go 1.18

require (
	github.com/go-co-op/gocron v1.15.0 // indirect
	github.com/robfig/cron/v3 v3.0.1 // indirect
	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
)
```

### Expected behavior

Scheduler should stop relatively quickly, blocking only to allow currently running jobs to complete.

**Comment by JohnRoesler** [comment]
I should have a fix up for this soon!
