### ISSUE TITLE
[BUG] - removeByCondition get "slice bounds out of range"

### ISSUE THREAD

**Issue by ridwanakf** [go-co-op/gocron#45]
### Describe the bug

Loop in `removeByCondition` (scheduler.go) will keep iterating by the original value because the range loop copies the values from the slice to a local variable n; updating n will not affect the slice. It will result in panic because `slice bounds out of range` when the index of iteration goes beyond the current length of `s.jobs`

### To Reproduce

1. Run example code
2. Will result in this error: 
```
2020-07-11 08:00:11 +0000 UTC
panic: runtime error: slice bounds out of range [11:10]

goroutine 1 [running]:
github.com/go-co-op/gocron.removeAtIndex(...)
	/home/ridwanakf/go/pkg/mod/github.com/go-co-op/gocron@v0.2.0/scheduler.go:248
github.com/go-co-op/gocron.(*Scheduler).removeByCondition(0xc000032100, 0xc000098da8)
	/home/ridwanakf/go/pkg/mod/github.com/go-co-op/gocron@v0.2.0/scheduler.go:218 +0x23b
github.com/go-co-op/gocron.(*Scheduler).Remove(0xc000032100, 0x4dfda0, 0x515080)
	/home/ridwanakf/go/pkg/mod/github.com/go-co-op/gocron@v0.2.0/scheduler.go:203 +0x66
main.main()
	/home/ridwanakf/go/src/github.com/ridwanakf/personal-go-projects/cron/main.go:78 +0x1340
exit status 2
```

### Version

commit SHA: 4cc1bfb73568aeb8048dac6902e6b43df7d089ae

### Expected behavior

Should delete all expected jobs without resulting in panic

**Comment by ridwanakf** [comment]
Can I make PR to fix this bug?
